export default [
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        logger: "readonly",
        state: "readonly",
        DOM: "readonly",
        showToast: "readonly",
        formatPrice: "readonly",
        makeStockKey: "readonly",
        makeDomSafeKey: "readonly",
        findAllWrappersByStockKey: "readonly",
        updateExistingCard: "readonly",
        APIClient: "readonly",
        sseManager: "readonly",
        updateIndicesBar: "readonly",
        updateStocksFromSseData: "readonly",
        debouncedRenderPortfolio: "readonly",
        renderStocks: "readonly",
        chartInstances: "readonly",
        getChartPref: "readonly",
        destroyChart: "readonly",
        toFiniteNumber: "readonly",
        sanitizeHexColor: "readonly",
        createEl: "readonly",
        getStockColor: "readonly",
        isValidHexColor: "readonly",
        registerWrapper: "readonly",
        unregisterWrapper: "readonly",
        toggleDetail: "readonly",
        openPortfolioModal: "readonly",
        openAlertModal: "readonly",
        sendChat: "readonly",
        updateStockColor: "readonly",
        CONSTANTS: "readonly",
        setChartPref: "readonly",
        refreshStockChart: "readonly",
        scheduleCompactLayoutAfterTransition: "readonly",
        analyzeStock: "readonly",
        drawSparkline: "readonly",
        drawChart: "readonly",
        drawPnLChart: "readonly",
        hasFreshSparklineData: "readonly",
        isSparklineHidden: "readonly",
        setSparklineVisibility: "readonly",
        shouldUpdateSparkline: "readonly",
        isElementInViewport: "readonly",
        checkAlerts: "readonly",
        triggerPriceFlash: "readonly",
        updatePortfolioInfoElements: "readonly",
        applySortOrder: "readonly",
        renderPortfolio: "readonly",
        renderFavorites: "readonly",
        EventSource: "readonly"
      }
    },
    rules: {
      "no-unused-vars": "off",
      "no-undef": "off"
    }
  }
];
