export default [
  {
    files: ["static/js/**/*.js", "chrome_extension/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      // The frontend scripts are classic (non-module) scripts loaded via multiple
      // <script> tags sharing a global scope (no import/export statements). Using
      // sourceType "script" matches the runtime model and eliminates the ~163
      // bogus no-undef/no-unused-vars warnings from cross-file globals. (M-4)
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        HTMLElement: "readonly",
        CustomEvent: "readonly",
        Blob: "readonly",
        URL: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        DOMException: "readonly",
        Chart: "readonly",
        THREE: "readonly",
        chrome: "readonly",
        logger: "readonly",
        state: "readonly",
        DOM: "readonly",
        showToast: "readonly",
        formatPrice: "readonly",
        makeStockKey: "readonly",
        makeDomSafeKey: "readonly",
        findAllWrappersByStockKey: "readonly",
        updateExistingCard: "readonly",
        APIClient: "readonly",
        sseManager: "readonly",
        updateIndicesBar: "readonly",
        updateStocksFromSseData: "readonly",
        debouncedRenderPortfolio: "readonly",
        renderStocks: "readonly",
        chartInstances: "readonly",
        getChartPref: "readonly",
        destroyChart: "readonly",
        toFiniteNumber: "readonly",
        sanitizeHexColor: "readonly",
        createEl: "readonly",
        getStockColor: "readonly",
        isValidHexColor: "readonly",
        registerWrapper: "readonly",
        unregisterWrapper: "readonly",
        toggleDetail: "readonly",
        openPortfolioModal: "readonly",
        openAlertModal: "readonly",
        sendChat: "readonly",
        updateStockColor: "readonly",
        CONSTANTS: "readonly",
        setChartPref: "readonly",
        refreshStockChart: "readonly",
        scheduleCompactLayoutAfterTransition: "readonly",
        analyzeStock: "readonly",
        drawSparkline: "readonly",
        drawChart: "readonly",
        drawPnLChart: "readonly",
        hasFreshSparklineData: "readonly",
        isSparklineHidden: "readonly",
        setSparklineVisibility: "readonly",
        shouldUpdateSparkline: "readonly",
        isElementInViewport: "readonly",
        checkAlerts: "readonly",
        triggerPriceFlash: "readonly",
        updatePortfolioInfoElements: "readonly",
        applySortOrder: "readonly",
        renderPortfolio: "readonly",
        renderFavorites: "readonly",
        EventSource: "readonly",
        getSseMode: "readonly",
        updateSseModeSelectorUI: "readonly",
        setSseMode: "readonly",
        TradingViewManager: "readonly",
        apiFetch: "readonly",
        csrfFetch: "readonly",
        readCsrfToken: "readonly",
        loadNews: "readonly",
        forceRefreshNews: "readonly",
        searchStocks: "readonly",
        addStock: "readonly",
        addStockPrompt: "readonly",
        normalizeSymbolForMarketClient: "readonly",
        sleep: "readonly",
        fetchInitialStocks: "readonly",
        loadTrending: "readonly",
        connectSSE: "readonly",
        sseApiClient: "readonly",
        pollingManager: "readonly",
        applyAnalysisResult: "readonly",
        bulkAnalyzeFavorites: "readonly",
        HAS_MISTRAL_API_KEY: "readonly",
        DEFAULT_SYMBOLS: "readonly",
        APP_CONFIG: "readonly",
        IntersectionObserver: "readonly",
        AbortController: "readonly",
        URLSearchParams: "readonly",
        stockDetailsCache: "writable",
        renderDetailExtras: "readonly",
        stockRealtimeUpdateAt: "writable",
        getStockByKey: "readonly",
        detailCloseGeneration: "writable",
        compactStockCardLayout: "readonly",
        getTransitionFallbackMs: "readonly",
        clearStockCardMinHeights: "readonly",
        sseState: "readonly",
        renderSkeletons: "readonly",
        renderInitialLoadingTimeoutState: "readonly",
        wrapperRegistryMap: "readonly",
        portfolioChartCache: "writable",
        computeHoldingsHash: "readonly",
        resolvePortfolioChartAnimationControl: "readonly",
        portfolioFixedExchangeRate: "readonly",
        buildLocalDateKey: "readonly",
        getSortOrder: "readonly",
        orderIndex: "readonly",
        formatMarketCap: "readonly",
        isBlankDetailValue: "readonly",
        setDetailItemVisibility: "readonly",
        setBulkAnalyzeStatus: "readonly",
        showChartError: "readonly",
        getSparklineSignature: "readonly",
        sparklineSignatureMap: "readonly",
        getDatasetHiddenStateByLabel: "readonly",
        applyDatasetHiddenStateByLabel: "readonly",
        validateSymbol: "readonly",
        validateNumberInput: "readonly",
        sanitizeTextInput: "readonly",
        parseRequiredNonNegativeNumber: "readonly",
        parseOptionalNonNegativeNumber: "readonly",
        setButtonLoading: "readonly",
        resetButton: "readonly",
        openModal: "readonly",
        clearLegacyBrowserCredentials: "readonly",
        createRequestToken: "readonly",
        CHAT_POLL_MAX_ATTEMPTS: "readonly",
        CHAT_POLL_INTERVAL_MS: "readonly",
        // Remaining cross-file globals & browser globals surfaced after the
        // module->script sourceType fix (M-4). Functions/consts are readonly;
        // module-level mutable state shared between files is writable.
        APIError: "readonly",
        INITIAL_SKELETON_MAX_WAIT_MS: "readonly",
        Notification: "readonly",
        _enforcePrefetchCacheLimit: "readonly",
        applyHistoryToStockAndWrapper: "readonly",
        clearChartError: "readonly",
        clearLegacyApiKeyStorage: "readonly",
        closeModal: "readonly",
        confirm: "readonly",
        getChartAnimationEnabled: "readonly",
        getHistoryPrefetchKey: "readonly",
        handleYfinanceRateLimitStatus: "readonly",
        loadIndicesLoop: "readonly",
        mergeStocksWithExistingHistory: "readonly",
        normalizeHistoryData: "readonly",
        refreshCredentialState: "readonly",
        renderTrendingBadges: "readonly",
        scheduleHistoryPrefetchWarmup: "readonly",
        setActiveTab: "readonly",
        stopSseFallbackPolling: "readonly",
        updateApiStatus: "readonly",
        updateTabCounts: "readonly",
        historyPrefetchCache: "writable",
        historyPrefetchInFlight: "writable",
        historyPrefetchJobTimers: "writable",
        historyPrefetchLastRunAt: "writable",
        historyPrefetchTimer: "writable",
        stockHashMap: "writable",
        getFreshPrefetchedHistory: "readonly",
        getColorSchemePreference: "readonly",
        initThemeColorScheme: "readonly",
      },
    },
    rules: {
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          // Classic scripts share one global scope, so top-level declarations
          // are legitimately consumed by other files. Only check locals to
          // avoid false positives for cross-file globals. (M-4)
          vars: "local",
        },
      ],
      "no-undef": "warn",
    },
  },
];
