[pytest]
filterwarnings =
    error::ResourceWarning
addopts = --tb=short -q -n auto --dist=loadfile
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    unit: marks tests as unit tests
    integration: marks tests as integration tests
    regression: marks tests as regression tests
    coverage: marks tests as coverage-boosting tests
    network: marks tests that require network access
