"""Predefined sector and industry mappings for known stock tickers.

Single source of truth for static ticker metadata used across the application.
"""

PREDEFINED_SECTORS = {
    # US
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Communication Services",
    "AMZN": "Consumer Cyclical",
    "NVDA": "Technology",
    "TSLA": "Consumer Cyclical",
    "META": "Communication Services",
    "NFLX": "Communication Services",
    "AVGO": "Technology",
    "ADBE": "Technology",
    "COST": "Consumer Defensive",
    "PEP": "Consumer Defensive",
    "CSCO": "Technology",
    "INTC": "Technology",
    "TMUS": "Communication Services",
    "CMCSA": "Communication Services",
    "AMD": "Technology",
    "TXN": "Technology",
    "HON": "Industrials",
    "QCOM": "Technology",
    "BRK-B": "Financial Services",
    "V": "Financial Services",
    "JNJ": "Healthcare",
    "WMT": "Consumer Defensive",
    "JPM": "Financial Services",
    "PG": "Consumer Defensive",
    "MA": "Financial Services",
    "UNH": "Healthcare",
    "HD": "Consumer Cyclical",
    "XOM": "Energy",
    # JP
    "7203.T": "Consumer Cyclical",
    "6758.T": "Consumer Cyclical",
    "9984.T": "Communication Services",
    "8306.T": "Financial Services",
    "6861.T": "Technology",
    "6098.T": "Industrials",
    "9432.T": "Communication Services",
    "8035.T": "Technology",
    "4502.T": "Healthcare",
    "7974.T": "Consumer Cyclical",
    "6501.T": "Industrials",
    "6954.T": "Industrials",
    "8001.T": "Industrials",
    "8058.T": "Industrials",
    "8316.T": "Financial Services",
    "4063.T": "Technology",
    "6702.T": "Technology",
    "6902.T": "Consumer Cyclical",
    "6367.T": "Industrials",
    "4568.T": "Healthcare",
    "6503.T": "Technology",
    "8766.T": "Financial Services",
    "6273.T": "Industrials",
    "6178.T": "Financial Services",
    "9022.T": "Industrials",
    "7267.T": "Consumer Cyclical",
    "8591.T": "Financial Services",
    "6301.T": "Industrials",
    "4519.T": "Healthcare",
    "6701.T": "Technology",
}

PREDEFINED_INDUSTRIES = {
    # US
    "AAPL": "Consumer Electronics",
    "MSFT": "Software—Infrastructure",
    "GOOGL": "Internet Content & Information",
    "AMZN": "Internet Retail",
    "NVDA": "Semiconductors",
    "TSLA": "Auto Manufacturers",
    "META": "Internet Content & Information",
    "NFLX": "Entertainment",
    "AVGO": "Semiconductors",
    "ADBE": "Software—Application",
    "COST": "Discount Stores",
    "PEP": "Beverages—Non-Alcoholic",
    "CSCO": "Communication Equipment",
    "INTC": "Semiconductors",
    "TMUS": "Telecom Services",
    "CMCSA": "Entertainment",
    "AMD": "Semiconductors",
    "TXN": "Semiconductors",
    "HON": "Conglomerates",
    "QCOM": "Semiconductors",
    "BRK-B": "Financial Conglomerates",
    "V": "Credit Services",
    "JNJ": "Drug Manufacturers—General",
    "WMT": "Discount Stores",
    "JPM": "Banks—Diversified",
    "PG": "Household & Personal Products",
    "MA": "Credit Services",
    "UNH": "Healthcare Plans",
    "HD": "Home Improvement Retail",
    "XOM": "Oil & Gas Integrated",
    # JP
    "7203.T": "Auto Manufacturers",
    "6758.T": "Consumer Electronics",
    "9984.T": "Telecom Services",
    "8306.T": "Banks—Regional",
    "6861.T": "Scientific & Technical Instruments",
    "6098.T": "Staffing & Employment Services",
    "9432.T": "Telecom Services",
    "8035.T": "Semiconductor Equipment & Materials",
    "4502.T": "Drug Manufacturers—General",
    "7974.T": "Electronic Gaming & Multimedia",
    "6501.T": "Conglomerates",
    "6954.T": "Industrial Machinery",
    "8001.T": "Conglomerates",
    "8058.T": "Conglomerates",
    "8316.T": "Banks—Regional",
    "4063.T": "Specialty Chemicals",
    "6702.T": "Information Technology Services",
    "6902.T": "Auto Parts",
    "6367.T": "Building Products & Equipment",
    "4568.T": "Drug Manufacturers—General",
    "6503.T": "Information Technology Services",
    "8766.T": "Insurance—Diversified",
    "6273.T": "Industrial Machinery",
    "6178.T": "Insurance—Diversified",
    "9022.T": "Railroads",
    "7267.T": "Auto Manufacturers",
    "8591.T": "Credit Services",
    "6301.T": "Farm & Heavy Construction Machinery",
    "4519.T": "Drug Manufacturers—General",
    "6701.T": "Information Technology Services",
}

PREDEFINED_NAMES = {
    # US
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc.",
    "AMZN": "Amazon.com Inc.",
    "NVDA": "NVIDIA Corporation",
    "TSLA": "Tesla Inc.",
    "META": "Meta Platforms Inc.",
    "NFLX": "Netflix Inc.",
    "AVGO": "Broadcom Inc.",
    "ADBE": "Adobe Inc.",
    "COST": "Costco Wholesale Corp.",
    "PEP": "PepsiCo Inc.",
    "CSCO": "Cisco Systems Inc.",
    "INTC": "Intel Corporation",
    "TMUS": "T-Mobile US Inc.",
    "CMCSA": "Comcast Corp.",
    "AMD": "Advanced Micro Devices Inc.",
    "TXN": "Texas Instruments Inc.",
    "HON": "Honeywell International Inc.",
    "QCOM": "Qualcomm Inc.",
    "BRK-B": "Berkshire Hathaway Inc.",
    "V": "Visa Inc.",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "PG": "Procter & Gamble Co.",
    "MA": "Mastercard Inc.",
    "UNH": "UnitedHealth Group Inc.",
    "HD": "Home Depot Inc.",
    "XOM": "Exxon Mobil Corp.",
    # JP
    "7203.T": "トヨタ自動車",
    "6758.T": "ソニーグループ",
    "9984.T": "ソフトバンクグループ",
    "8306.T": "三菱UFJフィナンシャルG",
    "6861.T": "キーエンス",
    "6098.T": "リクルートHD",
    "9432.T": "日本電信電話 (NTT)",
    "8035.T": "東京エレクトロン",
    "4502.T": "武田薬品工業",
    "7974.T": "任天堂",
    "6501.T": "日立製作所",
    "6954.T": "ファナック",
    "8001.T": "伊藤忠商事",
    "8058.T": "三菱商事",
    "8316.T": "三井住友フィナンシャルG",
    "4063.T": "信越化学工業",
    "6702.T": "富士通",
    "6902.T": "デンソー",
    "6367.T": "ダイキン工業",
    "4568.T": "第一三共",
    "6503.T": "三菱電機",
    "8766.T": "東京海上HD",
    "6273.T": "SMC",
    "6178.T": "日本郵政",
    "9022.T": "JR東海",
    "7267.T": "本田技研工業 (ホンダ)",
    "8591.T": "オリックス",
    "6301.T": "小松製作所",
    "4519.T": "中外製薬",
    "6701.T": "日本電気 (NEC)",
}

PREDEFINED_MARKET_CAPS = {
    # US (USD)
    "AAPL": 3.3e12,
    "MSFT": 3.2e12,
    "GOOGL": 2.2e12,
    "AMZN": 1.9e12,
    "NVDA": 3.1e12,
    "TSLA": 6.0e11,
    "META": 1.2e12,
    "NFLX": 2.8e11,
    "AVGO": 6.5e11,
    "ADBE": 2.2e11,
    "COST": 3.2e11,
    "PEP": 2.3e11,
    "CSCO": 1.9e11,
    "INTC": 1.3e11,
    "TMUS": 2.0e11,
    "CMCSA": 1.6e11,
    "AMD": 2.5e11,
    "TXN": 1.5e11,
    "HON": 1.3e11,
    "QCOM": 1.8e11,
    "BRK-B": 8.8e11,
    "V": 5.6e11,
    "JNJ": 3.8e11,
    "WMT": 4.8e11,
    "JPM": 5.6e11,
    "PG": 3.8e11,
    "MA": 4.2e11,
    "UNH": 4.8e11,
    "HD": 3.6e11,
    "XOM": 5.0e11,
    # JP (JPY)
    "7203.T": 4.5e13,
    "6758.T": 1.6e13,
    "9984.T": 1.3e13,
    "8306.T": 1.5e13,
    "6861.T": 1.5e13,
    "6098.T": 1.0e13,
    "9432.T": 1.4e13,
    "8035.T": 1.2e13,
    "4502.T": 6.5e12,
    "7974.T": 9.0e12,
    "6501.T": 1.3e13,
    "6954.T": 4.0e12,
    "8001.T": 1.0e13,
    "8058.T": 1.1e13,
    "8316.T": 1.0e13,
    "4063.T": 1.0e13,
    "6702.T": 5.0e12,
    "6902.T": 7.0e12,
    "6367.T": 6.0e12,
    "4568.T": 9.0e12,
    "6503.T": 5.0e12,
    "8766.T": 8.0e12,
    "6273.T": 4.0e12,
    "6178.T": 5.0e12,
    "9022.T": 3.0e12,
    "7267.T": 7.0e12,
    "8591.T": 4.0e12,
    "6301.T": 4.0e12,
    "4519.T": 8.0e12,
    "6701.T": 3.5e12,
}

