"""Predefined sector and industry mappings for known stock tickers.

Single source of truth for static ticker metadata used across the application.
"""

PREDEFINED_SECTORS = {
    # US
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Communication Services",
    "AMZN": "Consumer Cyclical",
    "NVDA": "Technology",
    "TSLA": "Consumer Cyclical",
    "META": "Communication Services",
    "NFLX": "Communication Services",
    "AVGO": "Technology",
    "ADBE": "Technology",
    "COST": "Consumer Defensive",
    "PEP": "Consumer Defensive",
    "CSCO": "Technology",
    "INTC": "Technology",
    "TMUS": "Communication Services",
    "CMCSA": "Communication Services",
    "AMD": "Technology",
    "TXN": "Technology",
    "HON": "Industrials",
    "QCOM": "Technology",
    "BRK-B": "Financial Services",
    "V": "Financial Services",
    "JNJ": "Healthcare",
    "WMT": "Consumer Defensive",
    "JPM": "Financial Services",
    "PG": "Consumer Defensive",
    "MA": "Financial Services",
    "UNH": "Healthcare",
    "HD": "Consumer Cyclical",
    "XOM": "Energy",
    # JP
    "7203.T": "Consumer Cyclical",
    "6758.T": "Consumer Cyclical",
    "9984.T": "Communication Services",
    "8306.T": "Financial Services",
    "6861.T": "Technology",
    "6098.T": "Industrials",
    "9432.T": "Communication Services",
    "8035.T": "Technology",
    "4502.T": "Healthcare",
    "7974.T": "Consumer Cyclical",
    "6501.T": "Industrials",
    "6954.T": "Industrials",
    "8001.T": "Industrials",
    "8058.T": "Industrials",
    "8316.T": "Financial Services",
    "4063.T": "Technology",
    "6702.T": "Technology",
    "6902.T": "Consumer Cyclical",
    "6367.T": "Industrials",
    "4568.T": "Healthcare",
    "6503.T": "Technology",
    "8766.T": "Financial Services",
    "6273.T": "Industrials",
    "6178.T": "Financial Services",
    "9022.T": "Industrials",
    "7267.T": "Consumer Cyclical",
    "8591.T": "Financial Services",
    "6301.T": "Industrials",
    "4519.T": "Healthcare",
    "6701.T": "Technology",
}

PREDEFINED_INDUSTRIES = {
    # US
    "AAPL": "Consumer Electronics",
    "MSFT": "Software—Infrastructure",
    "GOOGL": "Internet Content & Information",
    "AMZN": "Internet Retail",
    "NVDA": "Semiconductors",
    "TSLA": "Auto Manufacturers",
    "META": "Internet Content & Information",
    "NFLX": "Entertainment",
    "AVGO": "Semiconductors",
    "ADBE": "Software—Application",
    "COST": "Discount Stores",
    "PEP": "Beverages—Non-Alcoholic",
    "CSCO": "Communication Equipment",
    "INTC": "Semiconductors",
    "TMUS": "Telecom Services",
    "CMCSA": "Entertainment",
    "AMD": "Semiconductors",
    "TXN": "Semiconductors",
    "HON": "Conglomerates",
    "QCOM": "Semiconductors",
    "BRK-B": "Financial Conglomerates",
    "V": "Credit Services",
    "JNJ": "Drug Manufacturers—General",
    "WMT": "Discount Stores",
    "JPM": "Banks—Diversified",
    "PG": "Household & Personal Products",
    "MA": "Credit Services",
    "UNH": "Healthcare Plans",
    "HD": "Home Improvement Retail",
    "XOM": "Oil & Gas Integrated",
    # JP
    "7203.T": "Auto Manufacturers",
    "6758.T": "Consumer Electronics",
    "9984.T": "Telecom Services",
    "8306.T": "Banks—Regional",
    "6861.T": "Scientific & Technical Instruments",
    "6098.T": "Staffing & Employment Services",
    "9432.T": "Telecom Services",
    "8035.T": "Semiconductor Equipment & Materials",
    "4502.T": "Drug Manufacturers—General",
    "7974.T": "Electronic Gaming & Multimedia",
    "6501.T": "Conglomerates",
    "6954.T": "Industrial Machinery",
    "8001.T": "Conglomerates",
    "8058.T": "Conglomerates",
    "8316.T": "Banks—Regional",
    "4063.T": "Specialty Chemicals",
    "6702.T": "Information Technology Services",
    "6902.T": "Auto Parts",
    "6367.T": "Building Products & Equipment",
    "4568.T": "Drug Manufacturers—General",
    "6503.T": "Information Technology Services",
    "8766.T": "Insurance—Diversified",
    "6273.T": "Industrial Machinery",
    "6178.T": "Insurance—Diversified",
    "9022.T": "Railroads",
    "7267.T": "Auto Manufacturers",
    "8591.T": "Credit Services",
    "6301.T": "Farm & Heavy Construction Machinery",
    "4519.T": "Drug Manufacturers—General",
    "6701.T": "Information Technology Services",
}
