"""
security_config.py - Centralized security configuration for Mistral NeX Stocks.

Consolidates Flask session settings, CSP, Talisman, and CSRF initialization
to reduce app.py complexity.
Exports:
    init_security(app)  - Configure session, CSP, Talisman, CSRF. Returns csrf object.
"""

import os
from datetime import timedelta

from flask import Flask
from flask_talisman import Talisman
from flask_wtf.csrf import CSRFProtect


def init_security(app: Flask) -> CSRFProtect:
    """Configure all security-related Flask settings in one call.

    Sets up session cookies, CSRF protection, Content Security Policy,
    Talisman security headers, and HSTS. Call once after app creation.

    Returns:
        CSRFProtect instance (needed for csrf.exempt() calls in app.py).
    """

    # ── セッション設定の強化（個人利用向け） ──
    # SESSION_COOKIE_SECURE: 環境変数 MNS_COOKIE_SECURE=1 または MNS_PROD=1 で有効化
    # 個人利用のlocalhost環境ではHTTP接続のためデフォルトはFalse
    from utils.env_helpers import _is_production_env

    # H-4: Transport security (Secure cookies, HSTS, force_https) must be
    # enabled not only in production but also whenever the API is exposed
    # beyond loopback — i.e. remote/reverse-proxy mode (MNS_ALLOW_REMOTE_API=1
    # with MNS_PROXY_FIX=1). Under that mode _is_local_request() returns True
    # for any proxied caller, so relying solely on MNS_PROD would leave session
    # cookies sent over plaintext HTTP and HSTS absent — a credential-theft
    # risk. Treat remote/proxy mode as production-equivalent for transport.
    # _is_production_env() already incorporates the remote+proxy check,
    # so no separate _remote_proxy computation is needed here.
    _is_prod_env = _is_production_env()
    _cookie_secure = _is_prod_env

    app.config.update(
        SESSION_COOKIE_HTTPONLY=True,             # JavaScriptからアクセス不可
        SESSION_COOKIE_SAMESITE="Lax",            # CSRF対策
        SESSION_COOKIE_SECURE=_cookie_secure,      # MNS_COOKIE_SECURE=1 or MNS_PROD=1 で有効化
        SESSION_COOKIE_PARTITIONED=_cookie_secure, # Flask 3.1+: Partitioned cookies (CHIPS) 対応
        PERMANENT_SESSION_LIFETIME=timedelta(seconds=3600),   # 1時間で期限切れ
        WTF_CSRF_TIME_LIMIT=3600,                  # CSRFトークンの有効期限（1時間）
        MAX_CONTENT_LENGTH=2 * 1024 * 1024,       # 2MB: DoS対策のコンテンツ長制限
                                              # (個人利用のみで、最大ボディはカスタムプロンプト5000文字/
                                              # チャット2000文字程度のため余裕を持たせつつ抑制)
        # Flask 3.1+ security defaults for form parsing
        MAX_FORM_MEMORY_SIZE=512 * 1024,           # 512KB: フォームデータのメモリ制限
        MAX_FORM_PARTS=1000,                        # 最大フォームパーツ数制限
    )

    # ── CSRF保護の初期化 ──
    csrf = CSRFProtect(app)

    # ── Content Security Policy (Strict CSP) ──
    # Strict CSP with nonce-based script execution:
    # - 'strict-dynamic' allows nonced scripts to load additional scripts
    #   without needing explicit hashes for each file.
    # - NO 'unsafe-inline' in script-src (defense against XSS via injection)
    # - style-src uses 'unsafe-inline' because inline styles from Chart.js
    #   and third-party libraries cannot be fully controlled via nonce.
    # - All inline event handlers have been migrated to addEventListener().
    # - Nonces are auto-generated by Flask-Talisman per request.
    # L-9: `report-uri` is deprecated in CSP Level 3 in favour of `report-to`
    # (paired with the `Reporting-Endpoints` response header). Until `report-to`
    # gains broader browser support, include both directives so that older
    # browsers fall back to `report-uri` while modern ones use `report-to`.
    _connect_src = "connect-src 'self'"
    if not _is_prod_env:
        _connect_src += " http://localhost:* http://127.0.0.1:*"

    CSP_DEFAULT_POLICY = os.environ.get(
        "CSP_DEFAULT_POLICY",
        f"default-src 'self'; "
        # strict-dynamic + nonce でスクリプトを制御。URLホワイトリストは
        # strict-dynamic 下では Chrome で無視されるため含めない。
        # CDNライブラリは nonce 付き <script> タグで読み込む。
        f"script-src 'self' 'strict-dynamic'; "
        f"style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; "
        f"img-src 'self' data: https:; "
        f"font-src 'self' https://fonts.gstatic.com; "
        f"{_connect_src}; "
        f"object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; "
        f"report-to csp-endpoint; "      # CSP Level 3 — modern browsers
        f"report-uri /api/csp-report;",  # Legacy fallback for older browsers
    )

    # M-2: Reporting-Endpoints header is injected in app.py's
    # add_extension_cors_headers() after_request handler to avoid
    # duplicate after_request registrations and ensure consistent ordering.
    # ``report-to`` requires a paired ``Reporting-Endpoints`` header.
    # Without this, browser-native reporting would be silently dropped.

    # ── Flask-Talismanによるセキュリティヘッダの一元管理 ──
    Talisman(
        app,
        content_security_policy=CSP_DEFAULT_POLICY,
        content_security_policy_nonce_in=["script-src"],
        force_https=_is_prod_env,                # 本番環境ではHTTPSを強制
        frame_options="DENY",
        strict_transport_security=_is_prod_env,
        session_cookie_secure=_cookie_secure,     # MNS_COOKIE_SECURE=1 or MNS_PROD=1 で有効化
        session_cookie_http_only=True,
        referrer_policy="strict-origin-when-cross-origin",
        # M-7: Permissions-Policy — 本アプリが使用しないブラウザ機能を明示的に無効化
        # ファイルアップロード/カメラ/マイク等は不要。clipboard-read はチャット入力用に許可。
        permissions_policy={
            "accelerometer": (),
            "ambient-light-sensor": (),
            "autoplay": (),
            "battery": (),
            "camera": (),
            "cross-origin-isolated": (),
            "display-capture": (),
            "document-domain": (),
            "encrypted-media": (),
            "execution-while-not-rendered": (),
            "execution-while-out-of-viewport": (),
            "fullscreen": (),
            "geolocation": (),
            "gyroscope": (),
            "magnetometer": (),
            "microphone": (),
            "midi": (),
            "navigation-override": (),
            "payment": (),
            "picture-in-picture": (),
            "publickey-credentials-get": (),
            "screen-wake-lock": (),
            "sync-xhr": (),
            "usb": (),
            "web-share": (),
            "xr-spatial-tracking": (),
        },
    )

    # CSP Report-Only モード（CSP_ENFORCE=false の場合）
    if os.environ.get("CSP_ENFORCE", "true").lower() not in ("1", "true", "yes"):
        app.config["TALISMAN_CONTENT_SECURITY_POLICY_REPORT_ONLY"] = True

    @app.context_processor
    def inject_csp_nonce():
        """Inject the CSP nonce into the template context.

        Flask-Talisman sets ``request.csp_nonce`` automatically.
        The ``g.csp_nonce`` fallback is unnecessary and removed.
        """
        from flask import g, request
        nonce = getattr(request, "csp_nonce", "") or ""
        if nonce:
            g.csp_nonce = nonce
        return dict(csp_nonce=nonce)

    app.logger.info(
        "Security initialised: prod=%s cookie_secure=%s csrf=%s",
        _is_prod_env,
        _cookie_secure,
        type(csrf).__name__,
    )

    return csrf
