# routes/api_stocks.py
"""Backward-compatible re-export facade for routes.stocks package.

All implementation has moved to `routes.stocks` subpackage:
- `routes.stocks.common`: Shared helpers and normalization
- `routes.stocks.quotes`: Quotes, indices, history, search, and details endpoints
- `routes.stocks.views`: Screener, heatmap, watchlist mutation endpoints
- `routes.stocks.portfolio`: Portfolio management and snapshot endpoints
- `routes.stocks.stream`: SSE connection ticket and streaming endpoints
- `routes.stocks.ai_portfolio`: AI portfolio generation and rebalancing endpoints
"""

from app_bg import (
    fetch_stocks_batch,
    schedule_sync_all_stocks_now,
)
from app_state import app_state
from constants import POPULAR_JP, POPULAR_US
from credential_manager import get_or_create_extension_api_token
from error_codes import ErrorCode, get_error_message
from route_helpers import (
    _parse_stock_request,
    _stock_display_name,
    _submit_in_app_context,
    ensure_stock_placeholder_in_caches,
    extract_api_key,
    invalidate_stock_caches,
    rate_limit,
    remove_stock_from_caches,
)
from routes.stocks import (
    _WATCHLIST_MARKET_LABELS,
    AI_PORTFOLIO_RESULT_CACHE_TTL,
    FetchJob,
    _announce_watchlist_state,
    _fetch_heatmap_cached,
    _json_safe,
    _parse_last_event_id,
    _replay_frame_for_entry,
    _run_async_info_fetch,
    _stored_symbol_aliases,
    _submit_async_history_fetch,
    _submit_async_info_fetch,
    _sync_realtime_symbol,
    _watchlist_capacity_error,
    _watchlist_has_capacity,
    ai_portfolio_bp,
    ai_portfolio_fetch_inflight,
    ai_portfolio_fetch_lock,
    ai_portfolio_result_cache,
    api_add_stock,
    api_add_stock_ext,
    api_copy_ai_portfolio_to_my,
    api_create_sse_ticket,
    api_delete_ai_portfolio,
    api_delete_stock,
    api_generate_ai_portfolio,
    api_get_ai_portfolios,
    api_heatmap,
    api_indices,
    api_portfolio_snapshot,
    api_rebalance_ai_portfolio,
    api_reset_stocks,
    api_save_ai_portfolio,
    api_screener,
    api_search,
    api_stock_details,
    api_stock_history,
    api_stocks,
    api_stocks_bp,
    api_stocks_stream,
    api_update_portfolio,
    portfolio_bp,
    quotes_bp,
    stream_bp,
    views_bp,
)
from services.ai_portfolio_service import (
    DEFAULT_PRESET_CONFIGS,
    MAX_AI_PORTFOLIO_ITEMS,
    VIRTUAL_INITIAL_CAPITAL_JPY,
    delete_custom_ai_portfolio,
    generate_ai_portfolio_by_theme,
    load_saved_ai_portfolios,
    sanitize_ai_portfolio,
    save_custom_ai_portfolio,
)
from services.market_data_service import (
    build_heatmap_payload,
    build_popular_symbol_items,
    build_screener_base_rows,
    build_screener_enrichment,
)
from services.stock_service import (
    fetch_history_async_task,
)
from utils.caching import (
    CACHE_FETCHING,
    _get_cached_value,
    _has_cached_key,
    clear_cache_prefix,
    get_cached,
)
from utils.market_utils import is_market_open
from utils.networking import (
    SSE_TICKET_TTL_SEC,
    SseTicketSessionUnavailable,
    _is_allowed_shutdown_origin,
    _is_local_request,
    _is_loopback_ip,
    create_sse_ticket,
    require_sse_auth,
    require_trusted_or_admin,
)
from utils.normalization import (
    is_valid_symbol,
    normalize_market,
    normalize_optional_number,
    normalize_symbol,
    normalize_symbol_for_market,
)
from utils.stock_payload import (
    _default_stock_names,
    _get_stock_container,
    _resolve_indices_for_response,
    _resolve_stocks_for_response,
    _stock_is_default_or_user,
    _wait_for_initial_market_snapshot,
    error_response,
    fetch_stock_info_async,
    get_current_usdjpy_rate,
    get_stock_info_cached,
)
from utils.storage import UserStocksPersistError, save_user_stocks
from utils.text_utils import _parse_json_request, parse_non_negative_float
from utils.validators import validate_portfolio_input

__all__ = [
    "AI_PORTFOLIO_RESULT_CACHE_TTL",
    "CACHE_FETCHING",
    "DEFAULT_PRESET_CONFIGS",
    "MAX_AI_PORTFOLIO_ITEMS",
    "POPULAR_JP",
    "POPULAR_US",
    "SSE_TICKET_TTL_SEC",
    "VIRTUAL_INITIAL_CAPITAL_JPY",
    "_WATCHLIST_MARKET_LABELS",
    "ErrorCode",
    "FetchJob",
    "SseTicketSessionUnavailable",
    "UserStocksPersistError",
    "_announce_watchlist_state",
    "_default_stock_names",
    "_fetch_heatmap_cached",
    "_get_cached_value",
    "_get_stock_container",
    "_has_cached_key",
    "_is_allowed_shutdown_origin",
    "_is_local_request",
    "_is_loopback_ip",
    "_json_safe",
    "_parse_json_request",
    "_parse_last_event_id",
    "_parse_stock_request",
    "_replay_frame_for_entry",
    "_resolve_indices_for_response",
    "_resolve_stocks_for_response",
    "_run_async_info_fetch",
    "_stock_display_name",
    "_stock_is_default_or_user",
    "_stored_symbol_aliases",
    "_submit_async_history_fetch",
    "_submit_async_info_fetch",
    "_submit_in_app_context",
    "_sync_realtime_symbol",
    "_wait_for_initial_market_snapshot",
    "_watchlist_capacity_error",
    "_watchlist_has_capacity",
    "ai_portfolio_bp",
    "ai_portfolio_fetch_inflight",
    "ai_portfolio_fetch_lock",
    "ai_portfolio_result_cache",
    "api_add_stock",
    "api_add_stock_ext",
    "api_copy_ai_portfolio_to_my",
    "api_create_sse_ticket",
    "api_delete_ai_portfolio",
    "api_delete_stock",
    "api_generate_ai_portfolio",
    "api_get_ai_portfolios",
    "api_heatmap",
    "api_indices",
    "api_portfolio_snapshot",
    "api_rebalance_ai_portfolio",
    "api_reset_stocks",
    "api_save_ai_portfolio",
    "api_screener",
    "api_search",
    "api_stock_details",
    "api_stock_history",
    "api_stocks",
    "api_stocks_bp",
    "api_stocks_stream",
    "api_update_portfolio",
    "app_state",
    "build_heatmap_payload",
    "build_popular_symbol_items",
    "build_screener_base_rows",
    "build_screener_enrichment",
    "clear_cache_prefix",
    "create_sse_ticket",
    "delete_custom_ai_portfolio",
    "ensure_stock_placeholder_in_caches",
    "error_response",
    "extract_api_key",
    "fetch_history_async_task",
    "fetch_stock_info_async",
    "fetch_stocks_batch",
    "generate_ai_portfolio_by_theme",
    "get_cached",
    "get_current_usdjpy_rate",
    "get_error_message",
    "get_or_create_extension_api_token",
    "get_stock_info_cached",
    "invalidate_stock_caches",
    "is_market_open",
    "is_valid_symbol",
    "load_saved_ai_portfolios",
    "normalize_market",
    "normalize_optional_number",
    "normalize_symbol",
    "normalize_symbol_for_market",
    "parse_non_negative_float",
    "portfolio_bp",
    "quotes_bp",
    "rate_limit",
    "remove_stock_from_caches",
    "require_sse_auth",
    "require_trusted_or_admin",
    "sanitize_ai_portfolio",
    "save_custom_ai_portfolio",
    "save_user_stocks",
    "schedule_sync_all_stocks_now",
    "stream_bp",
    "validate_portfolio_input",
    "views_bp",
]
