# services/realtime/__init__.py
"""Realtime Market Data Engine package for Mistral NeX Stocks."""

from services.realtime.engine import RealtimeMarketEngine
from services.realtime.scrapers import (
    MinkabuScraper,
    Nikkei225JPScraper,
    SBISecuritiesScraper,
    YahooJPRealtimeScraper,
    _BaseFallbackScraper,
)
from services.realtime.tv_client import TradingViewWSClient
from services.realtime.utils import (
    HAS_CURL_CFFI,
    HAS_WEBSOCKET_CLIENT,
    JP_AFTERNOON_END,
    JP_AFTERNOON_START,
    JP_MORNING_END,
    JP_MORNING_START,
    JST,
    PTS_CACHE_STALE_SECONDS,
    PTS_POLL_INTERVAL_ACTIVE,
    PTS_POLL_INTERVAL_IDLE,
    PTS_SESSION_END_DAY,
    PTS_SESSION_END_NIGHT,
    PTS_SESSION_START_DAY,
    PTS_SESSION_START_NIGHT,
    SCRAPER_BLOCK_STATUS_CODES,
    TickerPayload,
    WebSocketOpcode8Filter,
    _create_cffi_session,
    _dedupe_pts_symbols,
    _extract_next_data_quotes,
    _extract_pts_fields,
    _extract_pts_price_data,
    _get_yfinance_previous_close,
    _interruptible_sleep,
    _is_scraper_blocked,
    _is_yf_rate_limited,
    _mark_scraper_blocked_from_status,
    _normalize_tv_symbol,
    _parse_quote_number,
    _scraper_market_state,
    _tv_purge_key_variants,
    is_jp_market_open,
    is_pts_session,
)

# Global Singleton Instance
realtime_market_engine = RealtimeMarketEngine()

__all__ = [
    "HAS_CURL_CFFI",
    "HAS_WEBSOCKET_CLIENT",
    "JP_AFTERNOON_END",
    "JP_AFTERNOON_START",
    "JP_MORNING_END",
    "JP_MORNING_START",
    "JST",
    "PTS_CACHE_STALE_SECONDS",
    "PTS_POLL_INTERVAL_ACTIVE",
    "PTS_POLL_INTERVAL_IDLE",
    "PTS_SESSION_END_DAY",
    "PTS_SESSION_END_NIGHT",
    "PTS_SESSION_START_DAY",
    "PTS_SESSION_START_NIGHT",
    "SCRAPER_BLOCK_STATUS_CODES",
    "MinkabuScraper",
    "Nikkei225JPScraper",
    "RealtimeMarketEngine",
    "SBISecuritiesScraper",
    "TickerPayload",
    "TradingViewWSClient",
    "WebSocketOpcode8Filter",
    "YahooJPRealtimeScraper",
    "_BaseFallbackScraper",
    "_create_cffi_session",
    "_dedupe_pts_symbols",
    "_extract_next_data_quotes",
    "_extract_pts_fields",
    "_extract_pts_price_data",
    "_get_yfinance_previous_close",
    "_interruptible_sleep",
    "_is_scraper_blocked",
    "_is_yf_rate_limited",
    "_mark_scraper_blocked_from_status",
    "_normalize_tv_symbol",
    "_parse_quote_number",
    "_scraper_market_state",
    "_tv_purge_key_variants",
    "is_jp_market_open",
    "is_pts_session",
    "realtime_market_engine",
]
